imports:
    - { resource: 'defaults.yml' }

services:
    kasimi.sorttopics.sort_core:
        class: 'kasimi\sorttopics\core\sort_core'
        abstract: true
        calls:
            - ['set_language', ['@language']]
            - ['set_template_context', ['@template_context']]

    kasimi.sorttopics.viewforum_listener:
        class: 'kasimi\sorttopics\event\viewforum_listener'
        parent: 'kasimi.sorttopics.sort_core'
        arguments:
            - '@auth'
            - '@request'
            - '@config'
            - '%kasimi.sorttopics.sort_by%'
        tags:
            - { name: 'event.listener' }

    kasimi.sorttopics.ucp_listener:
        class: 'kasimi\sorttopics\event\ucp_listener'
        parent: 'kasimi.sorttopics.sort_core'
        arguments:
            - '@config'
        tags:
            - { name: 'event.listener' }

    kasimi.sorttopics.acp_listener:
        class: 'kasimi\sorttopics\event\acp_listener'
        arguments:
            - '@language'
            - '@request'
            - '@dbal.conn'
            - '@template'
            - '%kasimi.sorttopics.sort_by%'
            - '%kasimi.sorttopics.sort_order%'
        tags:
            - { name: 'event.listener' }

    kasimi.sorttopics.acp_controller:
        class: 'kasimi\sorttopics\controller\acp'
        arguments:
            - '@user'
            - '@language'
            - '@request'
            - '@config'
            - '@template'
            - '@log'
